### ISSUE TITLE
初始化的时候 有异常发生

### ISSUE THREAD

**Issue by HeartDawnWY** [adsazad/my_flutter_xmpp#1]
W/System.err(28495): org.jivesoftware.smack.SmackException: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
W/System.err(28495): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1076)
W/System.err(28495): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)
W/System.err(28495): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)
W/System.err(28495): 	at java.lang.Thread.run(Thread.java:919)
W/System.err(28495): Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
W/System.err(28495): 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:231)
W/System.err(28495): 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.waitForHandshake(ConscryptFileDescriptorSocket.java:476)
W/System.err(28495): 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.getInputStream(ConscryptFileDescriptorSocket.java:439)
W/System.err(28495): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.initReaderAndWriter(XMPPTCPConnection.java:658)
W/System.err(28495): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.proceedTLSReceived(XMPPTCPConnection.java:807)
W/System.err(28495): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$1200(XMPPTCPConnection.java:151)
W/System.err(28495): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1071)
W/System.err(28495): 	... 3 more
W/System.err(28495): Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
W/System.err(28495): 	at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:674)
W/System.err(28495): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:551)
W/System.err(28495): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:507)
W/System.err(28495): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:426)
W/System.err(28495): 	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:354)
W/System.err(28495): 	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
W/System.err(28495): 	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:89)
W/System.err(28495): 	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:224)
W/System.err(28495): 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(ConscryptFileDescriptorSocket.java:407)
W/System.err(28495): 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
W/System.err(28495): 	at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:387)
W/System.err(28495): 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:226)
W/System.err(28495): 	... 9 more
W/System.err(28495): Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
W/System.err(28495): 	... 21 more
W/AbstractXMPPConnection(28495): Connection XMPPTCPConnection[not-authenticated] (0) closed with error
W/AbstractXMPPConnection(28495): javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
W/AbstractXMPPConnection(28495): 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:231)
W/AbstractXMPPConnection(28495): 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.waitForHandshake(ConscryptFileDescriptorSocket.java:476)
W/AbstractXMPPConnection(28495): 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.getInputStream(ConscryptFileDescriptorSocket.java:439)
W/AbstractXMPPConnection(28495): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.initReaderAndWriter(XMPPTCPConnection.java:658)
W/AbstractXMPPConnection(28495): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.proceedTLSReceived(XMPPTCPConnection.java:807)
W/AbstractXMPPConnection(28495): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$1200(XMPPTCPConnection.java:151)
W/AbstractXMPPConnection(28495): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1071)
W/AbstractXMPPConnection(28495): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)
W/AbstractXMPPConnection(28495): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)
W/AbstractXMPPConnection(28495): 	at java.lang.Thread.run(Thread.java:919)
W/AbstractXMPPConnection(28495): Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
W/AbstractXMPPConnection(28495): 	at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:674)
W/AbstractXMPPConnection(28495): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:551)
W/AbstractXMPPConnection(28495): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:507)
W/AbstractXMPPConnection(28495): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:426)
W/AbstractXMPPConnection(28495): 	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:354)
W/AbstractXMPPConnection(28495): 	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
W/AbstractXMPPConnection(28495): 	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:89)
W/AbstractXMPPConnection(28495): 	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:224)
W/AbstractXMPPConnection(28495): 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(ConscryptFileDescriptorSocket.java:407)
W/AbstractXMPPConnection(28495): 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
W/AbstractXMPPConnection(28495): 	at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:387)
W/AbstractXMPPConnection(28495): 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:226)
W/AbstractXMPPConnection(28495): 	... 9 more
W/AbstractXMPPConnection(28495): Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

证书好像没有找到。

**Comment by adsazad** [comment]
is SSL mindatory on your server? 
if yes check if it is valid or not.

**Comment by adsazad** [comment]
also check this link out
